/** Generated by YAKINDU Statechart Tools code generator. */
package drinkingmachine-n-v2.defaultsm;

import drinkingmachine-n-v2.IStatemachine;
import java.util.LinkedList;
import java.util.List;
import java.util.Queue;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

public interface IDefaultSMStatemachine extends IStatemachine {
	public interface SCInterface {
	
		public void raiseCoffee();
		
		public void raiseExpresso();
		
		public void raiseTea();
		
		public void raiseSoup();
		
		public void raiseIcedTea();
		
		public void raiseCinquanteCents();
		
		public void raiseVingtCinqCents();
		
		public void raiseDixCents();
		
		public void raiseBip();
		
		public void raiseCancel();
		
		public void raiseTemperature();
		
		public void raiseSize();
		
		public void raiseSugar();
		
		public void raiseValidate();
		
		public boolean isRaisedDoCoffee();
		
		public boolean isRaisedDoExpresso();
		
		public boolean isRaisedDoTea();
		
		public boolean isRaisedDoSoup();
		
		public boolean isRaisedDoIcedTea();
		
		public boolean isRaisedUpdateTemperature();
		
		public boolean isRaisedUpdateSize();
		
		public boolean isRaisedUpdateSugar();
		
		public boolean isRaisedDoSelect();
		
		public boolean isRaisedDoPrepare();
		
		public boolean isRaisedDoPay();
		
		public boolean isRaisedDoCancel();
		
		public boolean isRaisedDoFinish();
		
		public boolean getSelection();
		
		public void setSelection(boolean value);
		
		public boolean getPay();
		
		public void setPay(boolean value);
		
	public List<SCInterfaceListener> getListeners();
	}
	
	public interface SCInterfaceListener {
	
		public void onDoCoffeeRaised();
		public void onDoExpressoRaised();
		public void onDoTeaRaised();
		public void onDoSoupRaised();
		public void onDoIcedTeaRaised();
		public void onUpdateTemperatureRaised();
		public void onUpdateSizeRaised();
		public void onUpdateSugarRaised();
		public void onDoSelectRaised();
		public void onDoPrepareRaised();
		public void onDoPayRaised();
		public void onDoCancelRaised();
		public void onDoFinishRaised();
		}
	
	public SCInterface getSCInterface();
	
}
