/** Generated by YAKINDU Statechart Tools code generator. */
package yakindu.defaultsm;

import yakindu.IStatemachine;
import yakindu.ITimerCallback;

public interface IDefaultSMStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public void raiseCoffee();
		
		public void raiseExpresso();
		
		public void raiseTea();
		
		public void raiseSoup();
		
		public void raiseIcedTea();
		
		public void raiseCinquanteCents();
		
		public void raiseVingtCinqCents();
		
		public void raiseDixCents();
		
		public void raiseBip();
		
		public void raiseCancel();
		
		public void raiseTemp();
		
		public void raiseSize();
		
		public void raiseSugar();
		
		public void raiseValidate();
		
		public boolean isRaisedDoCoffee();
		
		public boolean isRaisedDoExpresso();
		
		public boolean isRaisedDoTea();
		
		public boolean isRaisedDoSoup();
		
		public boolean isRaisedDoIcedTea();
		
		public boolean isRaisedDoTemp();
		
		public boolean isRaisedDoSize();
		
		public boolean isRaisedDoSugar();
		
		public boolean isRaisedDoSelect();
		
		public boolean isRaisedDoPrepare();
		
		public boolean isRaisedDoPay();
		
		public boolean isRaisedDoCancel();
		
		public boolean isRaisedDoFinish();
		
		public boolean getSelection();
		
		public void setSelection(boolean value);
		
		public boolean getPay();
		
		public void setPay(boolean value);
		
	}
	
	public SCInterface getSCInterface();
	
}
