/** Generated by YAKINDU Statechart Tools code generator. */
package yakindu.defaultsm;

import java.util.LinkedList;
import java.util.Queue;
import yakindu.IStatemachine;
import yakindu.ITimerCallback;

public interface IDefaultSMStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public void raiseCoffee();
		
		public void raiseExpresso();
		
		public void raiseTea();
		
		public void raiseSoup();
		
		public void raiseIcedTea();
		
		public void raiseCinquanteCents();
		
		public void raiseVingtCinqCents();
		
		public void raiseDixCents();
		
		public void raiseBip();
		
		public void raiseCancel();
		
		public void raiseTemp();
		
		public void raiseSize();
		
		public void raiseSugar();
		
		public void raiseValidate();
		
		public boolean isRaisedDoCoffee();
		
		public boolean isRaisedDoExpresso();
		
		public boolean isRaisedDoTea();
		
		public boolean isRaisedDoSoup();
		
		public boolean isRaisedDoIcedTea();
		
		public boolean isRaisedDoTemp();
		
		public boolean isRaisedDoSize();
		
		public boolean isRaisedDoSugar();
		
		public boolean isRaisedDoSelect();
		
		public boolean isRaisedDoPrepare();
		
		public boolean isRaisedDoPay();
		
		public boolean isRaisedDoCancel();
		
		public boolean isRaisedDoFinish();
		
		public boolean isRaisedDoReceipt();
		
		public boolean isRaisedDoPoor();
		
		public boolean isRaisedDoDosette();
		
		public boolean isRaisedDoGrain();
		
		public boolean isRaisedDoSachet();
		
		public boolean isRaisedDoGobelet();
		
		public boolean isRaisedDoHeat();
		
		public boolean isRaisedDoInfuse();
		
		public boolean isRaisedDoRetake();
		
		public String getMySelection();
		
		public void setMySelection(String value);
		
		public boolean getSelection();
		
		public void setSelection(boolean value);
		
		public boolean getPay();
		
		public void setPay(boolean value);
		
		public boolean getHot();
		
		public void setHot(boolean value);
		
		public boolean getPoor();
		
		public void setPoor(boolean value);
		
		public boolean getTaken();
		
		public void setTaken(boolean value);
		
		public void setSCInterfaceOperationCallback(SCInterfaceOperationCallback operationCallback);
	
	}
	
	public interface SCInterfaceOperationCallback {
	
		public String getSelection();
		
		public boolean isHot();
		
		public boolean isPay();
		
		public boolean isPoor();
		
		public boolean isTaken();
		
	}
	
	public SCInterface getSCInterface();
	
}
